// Generated by https://quicktype.io

export interface PokemonResultsResponse {
  count: number;
  next: string;
  previous: null;
  results: PokemonResponse[];
}

export interface PokemonResponse {
  name: string;
  url: string;
}
